FROM node:16

ENV COMMINT_PREFIX=INPUT_COMMIT_PREFIX
ENV API_TOKEN=INPUT_API_TOKEN
ENV PULL_NUMBER=GITHUB_EVENT_NUMBER
ENV OWNER=GITHUB_EVENT_REPOSITORY_OWNER
ENV REPO_NAME=GITHUB_EVENT_REPOSITORY_NAME

WORKDIR /release-action

COPY . /release-action

RUN yarn

RUN yarn build

CMD ["yarn", "start"]
